// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPpSh44uaYW6VDnPStO_H3quUPVzjNGg',
    appId: '1:681933456177:web:52f906c4ab4359e16ae610',
    messagingSenderId: '681933456177',
    projectId: 'toptech-1dc04',
    authDomain: 'toptech-1dc04.firebaseapp.com',
    storageBucket: 'toptech-1dc04.firebasestorage.app',
    measurementId: 'G-WE12KWCLH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDKlCvFmJs7Fk5qwrVtpew4lhgPKoIjw',
    appId: '1:681933456177:android:e6cad17da8ea84046ae610',
    messagingSenderId: '681933456177',
    projectId: 'toptech-1dc04',
    storageBucket: 'toptech-1dc04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dkLaZD0QJnGxkUds68Z97aC-AFMoHpo',
    appId: '1:681933456177:ios:52434c218c0aad5a6ae610',
    messagingSenderId: '681933456177',
    projectId: 'toptech-1dc04',
    storageBucket: 'toptech-1dc04.firebasestorage.app',
    iosBundleId: 'com.example.toptech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dkLaZD0QJnGxkUds68Z97aC-AFMoHpo',
    appId: '1:681933456177:ios:52434c218c0aad5a6ae610',
    messagingSenderId: '681933456177',
    projectId: 'toptech-1dc04',
    storageBucket: 'toptech-1dc04.firebasestorage.app',
    iosBundleId: 'com.example.toptech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOPpSh44uaYW6VDnPStO_H3quUPVzjNGg',
    appId: '1:681933456177:web:fc9ea38aa1c01e4d6ae610',
    messagingSenderId: '681933456177',
    projectId: 'toptech-1dc04',
    authDomain: 'toptech-1dc04.firebaseapp.com',
    storageBucket: 'toptech-1dc04.firebasestorage.app',
    measurementId: 'G-VYL4FQZ7QD',
  );
}
